"""fix address column typo in property

Revision ID: 2dcf368b072a
Revises: e5c50f353499
Create Date: 2026-08-15 18:23:02.753399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcf368b072a'
down_revision: Union[str, None] = 'e5c50f353499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('properties', sa.Column('address', sa.String(), nullable=False))
    op.drop_column('properties', 'addres')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('addres', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('properties', 'address')
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
